### ISSUE TITLE
required kernel release

### ISSUE THREAD

**Issue by joalmjoalm** [mruijter/btier-2.X#1]
In Readme it says 
"IMPORTANT: BTIER-2.X works / is supported with a very recent kernel!!!
Use at least 3.14 or higher."

But I get the error below on kernel 4.15. What I found at the link https://www.kernel.org/doc/html/ the function "blk_queue_flag_clear" is available from release 4.17.

Which is the lowest required kernel release for the btier 2.2.1 /master? 

btier-2.X-2.2.0/kernel/btier/btier_sysfs.c:199:4: error: implicit declaration of function ‘blk_queue_flag_clear’; did you mean ‘queue_flag_clear’? [-Werror=implicit-function-declaration]
    blk_queue_flag_clear(QUEUE_FLAG_DISCARD,
    ^~~~~~~~~~~~~~~~~~~~
    queue_flag_clear
xxxx/btier-2.X-2.2.0/kernel/btier/btier_sysfs.c:211:4: error: implicit declaration of function ‘blk_queue_flag_set’; did you mean ‘queue_flag_set’? [-Werror=implicit-function-declaration]
    blk_queue_flag_set(QUEUE_FLAG_DISCARD,
    ^~~~~~~~~~~~~~~~~~
    queue_flag_set

**Comment by mruijter** [comment]
Hi Joalmjoalm,

I made a change which now allows me to compile btier with Ubuntu 18.04.
Tested with kernel : 4.15.0-96-generic #97-Ubuntu

The Ubuntu kernel differs from the stock 4.15.0 kernel. Please set the #define UBUNTU in kernel/btier/btier.h should you need to compile btier with the Ubuntu kernel.

**Comment by joalmjoalm** [comment]
I made some progress with uncommen of "define UBUNTU" but get these errors later in in the compiling. Is it related to that I in dir usr/src/ only have headers, Do I need to point to full soucre?

make -Wall -C /lib/modules/4.15.0-65-generic/build M=/home/jonas/btier/btier-2.X-master/kernel/btier modules
make[1]: Entering directory '/usr/src/linux-headers-4.15.0-65-generic'
  CC [M]  /home/jonas/btier/btier-2.X-master/kernel/btier/btier_common.o
  CC [M]  /home/jonas/btier/btier-2.X-master/kernel/btier/btier_sysfs.o
  CC [M]  /home/jonas/btier/btier-2.X-master/kernel/btier/btier_main.o
/home/jonas/btier/btier-2.X-master/kernel/btier/btier_main.c: In function ‘order_devices’:
/home/jonas/btier/btier-2.X-master/kernel/btier/btier_main.c:1590:10: error: too few arguments to function ‘lookup_bdev’
   bdev = lookup_bdev(dev->backdev[i]->devmagic->fullpathname);
          ^~~~~~~~~~~
In file included from ./include/linux/highmem.h:5:0,
                 from ./include/linux/bio.h:21,
                 from /home/jonas/btier/btier-2.X-master/kernel/btier/btier.h:12,
                 from /home/jonas/btier/btier-2.X-master/kernel/btier/btier_main.c:20:
./include/linux/fs.h:2578:29: note: declared here
 extern struct block_device *lookup_bdev(const char *, int mask);
                             ^~~~~~~~~~~
/home/jonas/btier/btier-2.X-master/kernel/btier/btier_main.c: In function ‘tier_set_fd’:
/home/jonas/btier/btier-2.X-master/kernel/btier/btier_main.c:1922:16: error: too few arguments to function ‘lookup_bdev’
         bdev = lookup_bdev(fullname);
                ^~~~~~~~~~~
In file included from ./include/linux/highmem.h:5:0,
                 from ./include/linux/bio.h:21,
                 from /home/jonas/btier/btier-2.X-master/kernel/btier/btier.h:12,
                 from /home/jonas/btier/btier-2.X-master/kernel/btier/btier_main.c:20:
./include/linux/fs.h:2578:29: note: declared here
 extern struct block_device *lookup_bdev(const char *, int mask);
                             ^~~~~~~~~~~
scripts/Makefile.build:330: recipe for target '/home/jonas/btier/btier-2.X-master/kernel/btier/btier_main.o' failed
make[2]: *** [/home/jonas/btier/btier-2.X-master/kernel/btier/btier_main.o] Error 1
Makefile:1571: recipe for target '_module_/home/jonas/btier/btier-2.X-master/kernel/btier' failed
make[1]: *** [_module_/home/jonas/btier/btier-2.X-master/kernel/btier] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.15.0-65-generic'
Makefile:6: recipe for target 'default' failed
make: *** [default] Error 2

**Comment by joalmjoalm** [comment]
I put the #define UBUNTU outside the comments and I think it works. Please confirm that this is the output that confirms a successfull make. There is one warning that shows up. 

make -Wall -C /lib/modules/4.15.0-65-generic/build M=/home/jonas/btier/btier-2.X-master/kernel/btier modules
make[1]: Entering directory '/usr/src/linux-headers-4.15.0-65-generic'
  CC [M]  /home/jonas/btier/btier-2.X-master/kernel/btier/btier_common.o
  CC [M]  /home/jonas/btier/btier-2.X-master/kernel/btier/btier_sysfs.o
  CC [M]  /home/jonas/btier/btier-2.X-master/kernel/btier/btier_main.o
  CC [M]  /home/jonas/btier/btier-2.X-master/kernel/btier/btier_request.o
  LD [M]  /home/jonas/btier/btier-2.X-master/kernel/btier/btier.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /home/jonas/btier/btier-2.X-master/kernel/btier/btier.mod.o
  LD [M]  /home/jonas/btier/btier-2.X-master/kernel/btier/btier.ko
make[1]: Leaving directory '/usr/src/linux-headers-4.15.0-65-generic'
gcc -O2 -D_FILE_OFFSET_BITS=64 cli/btier_setup.c -o cli/btier_setup
gcc -O2 -D_FILE_OFFSET_BITS=64 cli/btier_inspect.c -o cli/btier_inspect
gcc -O2 tools/writetest.c -o tools/writetest
tools/writetest.c: In function ‘main’:
tools/writetest.c:66:8: warning: implicit declaration of function ‘gettimeofday’ [-Wimplicit-function-declaration]
  (void)gettimeofday(&start_time, NULL);
        ^~~~~~~~~~~~
gcc -O2 tools/show_block_details.c -o tools/show_block_details

**Comment by mruijter** [comment]
Yes, this looks good. And indeed you need to put the define outside the comments.
Ignore the warning for writetest.c, this is a benchmark tool only and not relevant.

**Comment by joalmjoalm** [comment]
ok, thank you
