### ISSUE TITLE
Problems compiling on Alma Linux 8.6 (RHEL 8 clone)

### ISSUE THREAD

**Issue by hbouma** [mruijter/btier-2.X#2]
Hi Mark,

I'm having problems trying to compile this on a fresh Alma Linux 8.6 install. I get the error when it hits part_stat_lock:

  CC [M]  /root/btier-2.X/kernel/btier/btier_request.o
In file included from ././include/linux/compiler_types.h:58,
                 from <command-line>:
/root/btier-2.X/kernel/btier/btier_request.c: In function 'tier_make_request':
./include/linux/compiler-gcc.h:16:19: error: expected expression before '__asm__'
 #define barrier() __asm__ __volatile__("": : :"memory")
                   ^~~~~~~
./include/linux/preempt.h:246:29: note: in expansion of macro 'barrier'
 #define preempt_disable()   barrier()
                             ^~~~~~~
./include/linux/genhd.h:323:26: note: in expansion of macro 'preempt_disable'
 #define part_stat_lock() preempt_disable()
                          ^~~~~~~~~~~~~~~
/root/btier-2.X/kernel/btier/btier_request.c:746:8: note: in expansion of macro 'part_stat_lock'
  cpu = part_stat_lock();
        ^~~~~~~~~~~~~~

I'm not sure what is wrong since that code has been around more or less since btier 1.3.11 and that its basically a linux header macro so it should be fine with the gcc version installed.  

The kernel is 4.18.0-372.16.1.el8_6.x86_64 - but it seems to have a lot of 5.x features as well. I had to edit reactivate_disk to be reactivate_disk_size for example. 

This also happens with 1.3.11 as well at the same spot. Any help would be greatly appreciated. Thanks!

Hal

**Comment by hbouma** [comment]
Switching to the 5.4 kernel on the elrepo also got it to compile so I dug deeper. It looks like linux changed the part_stat_lock in the kernel 2 years ago to use the preempt enable/disable macros instead and redhat has backported it already into their 4.18 kernel. The normal 5.4 kernel is older than this so it doesn't have the new macros. The new macro doesn't like it when you have cpu = part_stat_lock() . I just removed the cpu = and its fine again. (I don't program every day right now so silly stuff like this evades me longer than it should lol).

**Comment by mruijter** [comment]
> Switching to the 5.4 kernel on the elrepo also got it to compile so I dug deeper. It looks like linux changed the part_stat_lock in the kernel 2 years ago to use the preempt enable/disable macros instead and redhat has backported it already into their 4.18 kernel. The normal 5.4 kernel is older than this so it doesn't have the new macros. The new macro doesn't like it when you have cpu = part_stat_lock() . I just removed the cpu = and its fine again. (I don't program every day right now so silly stuff like this evades me longer than it should lol).

I assume that it all works now. Distros that port kernels changes from newer to older kernels can be problematic. I don't have the time to test all combinations. For now a close to 5.4 kernel (Ubuntu, SuSE) are the best choice. I still need to test with Ubuntu 22.04 and the latest vanilla kernels.

**Comment by hbouma** [comment]
Yeah, I mean this will be a future problem for you as more distros start using these mainline kernel changes from 2020. The cpu = part_stat_lock will error because they changed the underlining macros.

**Comment by hbouma** [comment]
Also, FYI, I had to change the kernel check the line below the part_stat_lock from the 5.x to 4,18 for RHEL 8

#if LINUX_VERSION_CODE >= KERNEL_VERSION(5,0,0)
        part_stat_inc(&dev->gd->part0, ios[rw]);

I also had to change revalidate_disk to be revalidate_disk_size in register_new_device_size in btier_main.c 

Double FYI, mainline kernel has factored out genhd.h as well in January so it no longer exists.

I can create a RHEL define like you did with ubuntu and make these changes and submit them if you want. I also just wanted to say, I don't know if you remember my posts on sourceforge in 2016 from when I started using btier, but its been totally rock solid this whole time so thank you so much for writing this. Well, 1.3.11 has been solid, I'm hoping 2.x will be great this time around as I finally get off RHEL 6 for 8.  I haven't had any file system corruption this whole time even when my servers crash. I am still surprised that there still isn't anything like this out there. But thanks again for writing this!

**Comment by mruijter** [comment]
Should be working now when you define RHEL86
