### ISSUE TITLE
Another mainline backporting issue (bio_clone_fast)

### ISSUE THREAD

**Issue by hbouma** [mruijter/btier-2.X#3]
Hi,

Redhat backported another mainline kernel change from Feb 4th, 2022 that changed how bio_clone_fast behaves in RHEL 8. The mainline commit is here:

https://github.com/torvalds/linux/commit/56b4b5abcdab6daf71c5536fca2772f178590e06

I'm not sure what to use/set for the gfp_t allocation flags but I will try and look further when I have time. Any assistance would be appreciated. 

Hal

**Comment by mruijter** [comment]
This should be fairly easy to fix. I’ll post a fix later.

**Comment by hbouma** [comment]
Okay great, thanks for your help!

**Comment by mruijter** [comment]
Please pull the latest and define RHEL86 in btier.h
It should compile and work after that.

**Comment by hbouma** [comment]
Thanks. It compiles now. I'll be testing it soon and let you know if any issues come up.
